# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# Application Info
# ===============================
spring.application.name=notemind-backend

# ===============================
# PostgreSQL Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/notemate_db
spring.datasource.username=postgres
spring.datasource.password=215016G
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# File Upload Configuration (PDFs)
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# Swagger / OpenAPI Configuration
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger

# ===============================
# Logging (Optional but Useful)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# Security (Temporary ? Disable Default Login Page)
# ===============================
spring.security.user.name=admin
spring.security.user.password=admin
